
services:
  - type: web
    name: scraper-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: WEB_CONCURRENCY
        value: 4
    plan: free  # یا standard برای پروژه‌های حرفه‌ای
    healthCheckPath: /docs
